const API_BASE = "https://savvyrent-hud-api.abobroy.workers.dev";
const form=document.getElementById("rent-form"),submitButton=document.getElementById("submit-button"),formError=document.getElementById("form-error"),emptyState=document.getElementById("empty-state"),loadingState=document.getElementById("loading-state"),reportElement=document.getElementById("report");
document.getElementById("year").textContent=new Date().getFullYear();
form.addEventListener("submit",async e=>{e.preventDefault();clearError();showLoading(true);try{const payload=formPayload(new FormData(form));const response=await fetch(`${API_BASE}/api/rent-report`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){const validation=Array.isArray(data.validation)?`: ${data.validation.join("; ")}`:"";throw new Error(`${data.error||"Unable to create report"}${validation}`)}renderReport(data)}catch(error){showLoading(false);emptyState.classList.remove("hidden");showError(error.message.includes("Failed to fetch")?"The website could not reach the Rental Intelligence API. Confirm the Worker is deployed and that savvyrent.com is allowed by its CORS settings.":error.message)}});
function formPayload(fd){return compactObject({address:text(fd.get("address")),unitType:text(fd.get("unitType")),bedrooms:number(fd.get("bedrooms")),bathrooms:number(fd.get("bathrooms")),squareFeet:number(fd.get("squareFeet")),propertyType:text(fd.get("propertyType")),condition:text(fd.get("condition")),parking:text(fd.get("parking")),laundry:text(fd.get("laundry")),furnishing:text(fd.get("furnishing")),leaseStartDate:text(fd.get("leaseStartDate")),purchasePrice:number(fd.get("purchasePrice")),monthlyOperatingCosts:number(fd.get("monthlyOperatingCosts"))})}
function compactObject(v){return Object.fromEntries(Object.entries(v).filter(([,i])=>i!==undefined&&i!==null&&i!==""))}function text(v){return typeof v==="string"?v.trim():""}function number(v){if(v===""||v===null)return undefined;const p=Number(v);return Number.isFinite(p)?p:undefined}
function showLoading(on){submitButton.disabled=on;submitButton.querySelector("span").textContent=on?"Generating report…":"Generate rental report";emptyState.classList.add("hidden");reportElement.classList.add("hidden");loadingState.classList.toggle("hidden",!on)}
function renderReport(data){showLoading(false);reportElement.classList.remove("hidden");const valuation=data.valuation||{},neighborhood=data.neighborhood||{},tract=neighborhood.censusTract||{},hud=data.hud||{},investment=data.investment||{};setText("matched-address",data.location?.matchedAddress||data.input?.address||"Matched property");setText("quality-badge",`${data.dataQuality?.overall||"unknown"} data quality`);setText("estimated-rent",money(valuation.estimatedMonthlyRent));setText("rent-range",`${money(valuation.likelyRentRange?.low)} – ${money(valuation.likelyRentRange?.high)} likely range`);setText("confidence",`${valuation.confidenceScore??"—"}%`);setText("rent-per-sqft",valuation.rentPerSquareFoot?`$${valuation.rentPerSquareFoot.toFixed(2)}`:"—");setText("hud-fmr",money(hud.fairMarketRent));setText("acs-rent",money(tract.medianGrossRent));setText("trend-12",percent(neighborhood.trends?.rent12MonthPercent));setText("trend-36",percent(neighborhood.trends?.rent36MonthPercent));setText("vacancy",percent(tract.housing?.overallVacancyRate));setText("availability",percent(tract.housing?.rentalAvailabilityRate));setText("comparables-note",data.comparables?.explanation||"Live rental listings are not included in this public-data release.");renderAdjustments(valuation.adjustments||[]);renderInvestment(investment);document.getElementById("raw-json").textContent=JSON.stringify(data,null,2);reportElement.scrollIntoView({behavior:"smooth",block:"start"})}
function renderAdjustments(items){const c=document.getElementById("adjustments");c.innerHTML="";if(!items.length){c.textContent="No material property adjustments were applied.";return}for(const a of items){const pill=document.createElement("span");pill.className=`adjustment-pill ${a.percent>=0?"positive":"negative"}`;pill.textContent=`${labelize(a.factor)} ${a.percent>0?"+":""}${a.percent}%`;c.appendChild(pill)}}
function renderInvestment(i){const s=document.getElementById("investment-section"),has=i.grossRentMultiplier!==null&&i.grossRentMultiplier!==undefined;s.classList.toggle("hidden",!has);if(!has)return;setText("annual-gross",money(i.annualGrossRent));setText("noi",money(i.annualNetOperatingIncome));setText("grm",i.grossRentMultiplier?.toFixed(2)??"—");setText("cap-rate",i.capitalizationRatePercent!==null&&i.capitalizationRatePercent!==undefined?`${i.capitalizationRatePercent.toFixed(2)}%`:"—")}
function labelize(v){return String(v).replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}function money(v){return Number.isFinite(Number(v))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)):"—"}function percent(v){return Number.isFinite(Number(v))?`${Number(v)>0?"+":""}${Number(v).toFixed(1)}%`:"—"}function setText(id,v){document.getElementById(id).textContent=v??"—"}function showError(m){formError.textContent=m;formError.classList.remove("hidden")}function clearError(){formError.textContent="";formError.classList.add("hidden")}
